### PR TITLE
Add Windows compatibility

### PR DESCRIPTION
**Pull request by ghost**
This PR adds the appropriate documentation and code changes to allow the library to compile on Windows

### CODE REVIEW

**Comment by NobodyNada** [comment]
Awesome, thank you! I haven't tested it, but I'm assuming you have, and it looks pretty straightfoward :)

BTW the custom `swift build` command to set search paths on \*nix is outdated; since I wrote that documentation Swift gained the ability to automatically look up the appropriate search paths using `pkg-config`. I don't suppose that's possible on Windows?

**Comment by ghost** [comment]
It _can_m I just hadn't figured it out yet. I installed `pkg-config` on my Windows machine, but Swift wasn't picking it up and throwing a `warning: failed run pkg-config, check that it is installed` message, so not sure what's up there and it was working well enough with the arguments. 

Interestingly, now that you say that, do you have any ideas why this library won't compile in Xcode? I just get back a `Could not build Objective-C module 'Clibwebsockets'`, with or without the build flags from the `README` being added to the build settings

**Comment by ghost** [comment]
Also @NobodyNada, it looks like you'll need to tag a new release for these changes to take hold

**Comment by NobodyNada** [comment]
@ataffeqeexo So, it looks like the compiler doesn't know about the target dependency on `COpenSSL` (because there's no way to declare a dependency of a system library target). As a result, your project has to explicitly declare a dependency on [`NobodyNada/COpenSSL`](https://github.com/NobodyNada/COpenSSL) in order for it to compile.

I'll look today and see whether or not there's a better way to tell the compiler about the dependency; I'll create a release once I've done that! (If you want to work on a dependent in the meantime, you can set your Clibwebsockets dependency to `.branch("master")` instead of a version number.

**Comment by alex-taffe** [comment]
Ahh ok awesome, thanks, I’ll take a look

**Comment by alex-taffe** [comment]
@NobodyNada so I manually added the `COpenSSL` and `Clibuv` projects to my dependencies. `swift build` now works without the 9 million arguments, but Xcode is still angry. Still getting:

```
WebSocket.swift:11:8: Could not build Objective-C module ‘Clibwebsockets'
```
and
```
libwesockets:189: 'event2/event.h' file not found
```
Do you have any thoughts?

**Comment by NobodyNada** [comment]
@alex-taffe You might also need a dependency on `.package(url: "https://github.com/NobodyNada/Clibevent", from: "0.0.0")`; sorry I missed that one before.

**Comment by alex-taffe** [comment]
Ahh yep, that fixed it, thanks! I’ll create a documentation PR for that

**Pull request merged**
